services:
  website:
    container_name: website
    build: .
    restart: unless-stopped
    ports:
      - "8080:8080"
    environment:
      WEBSITE_TCP: 8080
      WEBSITE_UDS: /run/website/app.sock
    volumes:
      - "/run/website:/run/website"
      - "/etc/letsencrypt:/etc/letsencrypt:ro"
      - "./.git:/srv/website/.git:ro"
      - "./logs:/srv/website/logs"
      - "./databases:/srv/website/databases"
      - "./public:/srv/website/public:ro"
