services:
  website:
    container_name: website
    build: .
    restart: unless-stopped
    ports:
      - "80:80"
    volumes:
      - "./.git:/srv/website/.git:ro"
      - "./logs:/srv/website/logs"
      - "./databases:/srv/website/databases"
      - "./public:/srv/website/public:ro"
