[build-system]
requires = ["uv_build>=0.9.5,<0.10.0"]
build-backend = "uv_build"

[project]
name = "nercone-website"
version = "1.0.0"
requires-python = ">=3.12"
dependencies = [
    "nercone-aki",
    "httpx[http2]",

    "beautifulsoup4",
    "jinja2",
    "resvg-py",

    "mistune",
    "markitdown",

    "pyyaml",
    "tzdata",
    "fourword",

    "nercone-modern"
]

[project.scripts]
nercone-website = "nercone_website.__main__:main"
