[build-system]
requires = ["uv_build>=0.9.5,<0.10.0"]
build-backend = "uv_build"

[project]
name = "nercone-dev"
version = "1.0.0"
requires-python = ">=3.12"
dependencies = [
    "websockets",
    "httpx[http2]",
    "aioquic",

    "fastapi",
    "hypercorn[h3,uvloop]",

    "beautifulsoup4",

    "jinja2",
    "resvg-py",

    "mistune",
    "markitdown",

    "zstandard",
    "brotlicffi",

    "minify-html",
    "rcssmin",
    "rjsmin",
    "scour",

    "rich",
    "tzdata",
    "pyyaml",
    "fourword"
]

[tool.uv.sources]
aioquic = { git = "https://github.com/nercone-forks/aioquic", branch = "feature/pqc-support" }

[project.scripts]
nercone-dev = "nercone_dev.__main__:main"
